/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#f1f4f7",
        "primary": "#13197e",
        "error-container": "#ffdad6",
        "outline-variant": "#c6c5d4",
        "tertiary-container": "#2e3b7b",
        "on-tertiary": "#ffffff",
        "tertiary-fixed": "#dee1ff",
        "inverse-on-surface": "#eef1f4",
        "on-primary-fixed": "#00026c",
        "on-tertiary-container": "#9ba8ef",
        "on-secondary-fixed": "#00201d",
        "primary-fixed": "#e0e0ff",
        "on-secondary-container": "#006f67",
        "surface-tint": "#4d54b4",
        "on-surface-variant": "#464652",
        "surface-variant": "#e0e3e6",
        "on-primary-container": "#9ea5ff",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed-dim": "#b9c3ff",
        "on-error-container": "#93000a",
        "surface": "#f7fafd",
        "background": "#f7fafd",
        "tertiary": "#152464",
        "primary-fixed-dim": "#bec2ff",
        "on-tertiary-fixed": "#021355",
        "on-background": "#181c1e",
        "inverse-primary": "#bec2ff",
        "secondary-fixed-dim": "#71d7cd",
        "on-primary-fixed-variant": "#343b9b",
        "surface-bright": "#f7fafd",
        "primary-container": "#2d3494",
        "inverse-surface": "#2d3133",
        "surface-container-highest": "#e0e3e6",
        "outline": "#767683",
        "error": "#ba1a1a",
        "on-tertiary-fixed-variant": "#354282",
        "on-primary": "#ffffff",
        "surface-container": "#ebeef1",
        "surface-container-high": "#e5e8eb",
        "on-surface": "#181c1e",
        "surface-dim": "#d7dadd",
        "secondary-fixed": "#8ef4e9",
        "on-error": "#ffffff",
        "secondary-container": "#8bf1e6",
        "on-secondary-fixed-variant": "#00504a",
        "on-secondary": "#ffffff",
        "secondary": "#006a63",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "1.5rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
}
